### ISSUE TITLE
Add ability to "claim" a washer and dryer and be notified when its cycle finishes

### ISSUE THREAD

**Issue by mhoc** [Purdue-ACM-SIGAPP/PurdueLaundry#21] opened 2015-11-20 00:46 UTC
This would be useful for if I have laundry in and need to be notified when it is finished.

**Comment by bwencke** [comment] 2015-11-20 00:59
![notify when done](https://cloud.githubusercontent.com/assets/2365868/11289131/f0a6cc1a-8ef7-11e5-9be4-73812c53977a.png)

Click on a washer or dryer to see it in action: https://projects.invisionapp.com/share/BE43ZCS7N#/screens/100043833

**Comment by mhoc** [comment] 2015-11-20 00:59
:+1:

**Comment by bwencke** [comment] 2015-11-20 01:13
Notifications:
![washer timer](https://cloud.githubusercontent.com/assets/2365868/11289351/ee45811c-8ef9-11e5-9907-8fd80ac3487f.png)
![washer done](https://cloud.githubusercontent.com/assets/2365868/11289350/ee44e16c-8ef9-11e5-8ddc-7bbe72812a77.png)

**Comment by hughesjeff** [comment] 2015-11-30 06:40
Duplicate of issue #18

**Closed as completed by hughesjeff** 2015-11-30 06:40 UTC
Labels: enhancement
